//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `DepthEstimation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <DepthEstimation.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompDepthEstimation_DepthEstimation_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDepthEstimation::DepthEstimation"
};
const ::std::string iceC_RoboCompDepthEstimation_DepthEstimation_ops[] =
{
    "getDepthEstimation",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name = "getDepthEstimation";

}

bool
RoboCompDepthEstimation::DepthEstimation::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompDepthEstimation_DepthEstimation_ids, iceC_RoboCompDepthEstimation_DepthEstimation_ids + 2, s);
}

::std::vector<::std::string>
RoboCompDepthEstimation::DepthEstimation::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompDepthEstimation_DepthEstimation_ids[0], &iceC_RoboCompDepthEstimation_DepthEstimation_ids[2]);
}

::std::string
RoboCompDepthEstimation::DepthEstimation::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompDepthEstimation::DepthEstimation::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompDepthEstimation::DepthEstimation";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompDepthEstimation::DepthEstimation::_iceD_getDepthEstimation(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    auto istr = inS.startReadParams();
    TImage iceP_depthImg;
    istr->readAll(iceP_depthImg);
    inS.endReadParams();
    DepthScene iceP_result;
    this->getDepthEstimation(::std::move(iceP_depthImg), iceP_result, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_result);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDepthEstimation::DepthEstimation::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompDepthEstimation_DepthEstimation_ops, iceC_RoboCompDepthEstimation_DepthEstimation_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompDepthEstimation_DepthEstimation_ops)
    {
        case 0:
        {
            return _iceD_getDepthEstimation(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDepthEstimation::DepthEstimationPrx::_iceI_getDepthEstimation(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompDepthEstimation::DepthScene>>& outAsync, const TImage& iceP_depthImg, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name);
    outAsync->invoke(iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_depthImg);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompDepthEstimation::DepthEstimationPrx::_newInstance() const
{
    return ::IceInternal::createProxy<DepthEstimationPrx>();
}
/// \endcond

const ::std::string&
RoboCompDepthEstimation::DepthEstimationPrx::ice_staticId()
{
    return DepthEstimation::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name = "getDepthEstimation";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompDepthEstimation::upCast(DepthEstimation* p) { return p; }

void
::IceProxy::RoboCompDepthEstimation::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< DepthEstimation>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new DepthEstimation;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompDepthEstimation::DepthEstimation::_iceI_begin_getDepthEstimation(const ::RoboCompDepthEstimation::TImage& iceP_depthImg, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name, ::Ice::Idempotent, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_depthImg);
        result->endWriteParams();
        result->invoke(iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDepthEstimation::DepthEstimation::end_getDepthEstimation(::RoboCompDepthEstimation::DepthScene& iceP_result, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_result);
    result->_endReadParams();
}

void IceProxy::RoboCompDepthEstimation::DepthEstimation::_iceI_end_getDepthEstimation(::RoboCompDepthEstimation::DepthScene& iceP_result, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDepthEstimation_DepthEstimation_getDepthEstimation_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_result);
    result->_endReadParams();
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompDepthEstimation::DepthEstimation::_newInstance() const
{
    return new DepthEstimation;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompDepthEstimation::DepthEstimation::ice_staticId()
{
    return ::RoboCompDepthEstimation::DepthEstimation::ice_staticId();
}

RoboCompDepthEstimation::DepthEstimation::~DepthEstimation()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompDepthEstimation::upCast(DepthEstimation* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompDepthEstimation_DepthEstimation_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDepthEstimation::DepthEstimation"
};

}

bool
RoboCompDepthEstimation::DepthEstimation::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompDepthEstimation_DepthEstimation_ids, iceC_RoboCompDepthEstimation_DepthEstimation_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompDepthEstimation::DepthEstimation::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompDepthEstimation_DepthEstimation_ids[0], &iceC_RoboCompDepthEstimation_DepthEstimation_ids[2]);
}

const ::std::string&
RoboCompDepthEstimation::DepthEstimation::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompDepthEstimation::DepthEstimation::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompDepthEstimation::DepthEstimation";
    return typeId;
#else
    return iceC_RoboCompDepthEstimation_DepthEstimation_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompDepthEstimation::DepthEstimation::_iceD_getDepthEstimation(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    TImage iceP_depthImg;
    istr->read(iceP_depthImg);
    inS.endReadParams();
    DepthScene iceP_result;
    this->getDepthEstimation(iceP_depthImg, iceP_result, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_result);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompDepthEstimation_DepthEstimation_all[] =
{
    "getDepthEstimation",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompDepthEstimation::DepthEstimation::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompDepthEstimation_DepthEstimation_all, iceC_RoboCompDepthEstimation_DepthEstimation_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompDepthEstimation_DepthEstimation_all)
    {
        case 0:
        {
            return _iceD_getDepthEstimation(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompDepthEstimation::DepthEstimation::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< DepthEstimation, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompDepthEstimation::DepthEstimation::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< DepthEstimation, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDepthEstimation::_icePatchObjectPtr(DepthEstimationPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = DepthEstimationPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(DepthEstimation::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
