//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `DSRGetID.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <DSRGetID.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompDSRGetID_DSRGetID_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDSRGetID::DSRGetID"
};
const ::std::string iceC_RoboCompDSRGetID_DSRGetID_ops[] =
{
    "getID",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompDSRGetID_DSRGetID_getID_name = "getID";

}

bool
RoboCompDSRGetID::DSRGetID::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompDSRGetID_DSRGetID_ids, iceC_RoboCompDSRGetID_DSRGetID_ids + 2, s);
}

::std::vector<::std::string>
RoboCompDSRGetID::DSRGetID::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompDSRGetID_DSRGetID_ids[0], &iceC_RoboCompDSRGetID_DSRGetID_ids[2]);
}

::std::string
RoboCompDSRGetID::DSRGetID::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompDSRGetID::DSRGetID::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompDSRGetID::DSRGetID";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompDSRGetID::DSRGetID::_iceD_getID(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    int ret = this->getID(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDSRGetID::DSRGetID::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompDSRGetID_DSRGetID_ops, iceC_RoboCompDSRGetID_DSRGetID_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompDSRGetID_DSRGetID_ops)
    {
        case 0:
        {
            return _iceD_getID(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDSRGetID::DSRGetIDPrx::_iceI_getID(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDSRGetID_DSRGetID_getID_name);
    outAsync->invoke(iceC_RoboCompDSRGetID_DSRGetID_getID_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompDSRGetID::DSRGetIDPrx::_newInstance() const
{
    return ::IceInternal::createProxy<DSRGetIDPrx>();
}
/// \endcond

const ::std::string&
RoboCompDSRGetID::DSRGetIDPrx::ice_staticId()
{
    return DSRGetID::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompDSRGetID_DSRGetID_getID_name = "getID";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompDSRGetID::upCast(DSRGetID* p) { return p; }

void
::IceProxy::RoboCompDSRGetID::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< DSRGetID>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new DSRGetID;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompDSRGetID::DSRGetID::_iceI_begin_getID(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDSRGetID_DSRGetID_getID_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDSRGetID_DSRGetID_getID_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDSRGetID_DSRGetID_getID_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompDSRGetID_DSRGetID_getID_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Int
IceProxy::RoboCompDSRGetID::DSRGetID::end_getID(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDSRGetID_DSRGetID_getID_name);
    ::Ice::Int ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompDSRGetID::DSRGetID::_newInstance() const
{
    return new DSRGetID;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompDSRGetID::DSRGetID::ice_staticId()
{
    return ::RoboCompDSRGetID::DSRGetID::ice_staticId();
}

RoboCompDSRGetID::DSRGetID::~DSRGetID()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompDSRGetID::upCast(DSRGetID* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompDSRGetID_DSRGetID_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDSRGetID::DSRGetID"
};

}

bool
RoboCompDSRGetID::DSRGetID::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompDSRGetID_DSRGetID_ids, iceC_RoboCompDSRGetID_DSRGetID_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompDSRGetID::DSRGetID::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompDSRGetID_DSRGetID_ids[0], &iceC_RoboCompDSRGetID_DSRGetID_ids[2]);
}

const ::std::string&
RoboCompDSRGetID::DSRGetID::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompDSRGetID::DSRGetID::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompDSRGetID::DSRGetID";
    return typeId;
#else
    return iceC_RoboCompDSRGetID_DSRGetID_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompDSRGetID::DSRGetID::_iceD_getID(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Ice::Int ret = this->getID(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompDSRGetID_DSRGetID_all[] =
{
    "getID",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompDSRGetID::DSRGetID::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompDSRGetID_DSRGetID_all, iceC_RoboCompDSRGetID_DSRGetID_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompDSRGetID_DSRGetID_all)
    {
        case 0:
        {
            return _iceD_getID(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompDSRGetID::DSRGetID::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< DSRGetID, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompDSRGetID::DSRGetID::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< DSRGetID, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDSRGetID::_icePatchObjectPtr(DSRGetIDPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = DSRGetIDPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(DSRGetID::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
