//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `DifferentialRobot.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <DifferentialRobot.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDifferentialRobot::DifferentialRobot"
};
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_ops[] =
{
    "correctOdometer",
    "getBasePose",
    "getBaseState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "resetOdometer",
    "setOdometer",
    "setOdometerPose",
    "setSpeedBase",
    "stopBase"
};
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name = "getBaseState";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name = "getBasePose";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name = "setSpeedBase";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name = "stopBase";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name = "resetOdometer";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name = "setOdometer";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name = "setOdometerPose";
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name = "correctOdometer";

}

bool
RoboCompDifferentialRobot::DifferentialRobot::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompDifferentialRobot_DifferentialRobot_ids, iceC_RoboCompDifferentialRobot_DifferentialRobot_ids + 2, s);
}

::std::vector<::std::string>
RoboCompDifferentialRobot::DifferentialRobot::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[0], &iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[2]);
}

::std::string
RoboCompDifferentialRobot::DifferentialRobot::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompDifferentialRobot::DifferentialRobot::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompDifferentialRobot::DifferentialRobot";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_getBaseState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::RoboCompGenericBase::TBaseState iceP_state;
    this->getBaseState(iceP_state, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_state);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_getBasePose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    int iceP_x;
    int iceP_z;
    float iceP_alpha;
    this->getBasePose(iceP_x, iceP_z, iceP_alpha, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_x, iceP_z, iceP_alpha);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_setSpeedBase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    float iceP_adv;
    float iceP_rot;
    istr->readAll(iceP_adv, iceP_rot);
    inS.endReadParams();
    this->setSpeedBase(iceP_adv, iceP_rot, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_stopBase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->stopBase(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_resetOdometer(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->resetOdometer(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_setOdometer(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompGenericBase::TBaseState iceP_state;
    istr->readAll(iceP_state);
    inS.endReadParams();
    this->setOdometer(::std::move(iceP_state), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_setOdometerPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_x;
    int iceP_z;
    float iceP_alpha;
    istr->readAll(iceP_x, iceP_z, iceP_alpha);
    inS.endReadParams();
    this->setOdometerPose(iceP_x, iceP_z, iceP_alpha, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_correctOdometer(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_x;
    int iceP_z;
    float iceP_alpha;
    istr->readAll(iceP_x, iceP_z, iceP_alpha);
    inS.endReadParams();
    this->correctOdometer(iceP_x, iceP_z, iceP_alpha, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompDifferentialRobot_DifferentialRobot_ops, iceC_RoboCompDifferentialRobot_DifferentialRobot_ops + 12, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompDifferentialRobot_DifferentialRobot_ops)
    {
        case 0:
        {
            return _iceD_correctOdometer(in, current);
        }
        case 1:
        {
            return _iceD_getBasePose(in, current);
        }
        case 2:
        {
            return _iceD_getBaseState(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        case 7:
        {
            return _iceD_resetOdometer(in, current);
        }
        case 8:
        {
            return _iceD_setOdometer(in, current);
        }
        case 9:
        {
            return _iceD_setOdometerPose(in, current);
        }
        case 10:
        {
            return _iceD_setSpeedBase(in, current);
        }
        case 11:
        {
            return _iceD_stopBase(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_getBaseState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGenericBase::TBaseState>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_getBasePose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<DifferentialRobot::GetBasePoseResult>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        },
        [](::Ice::InputStream* istr)
        {
            DifferentialRobot::GetBasePoseResult v;
            istr->readAll(v.x, v.z, v.alpha);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_setSpeedBase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, float iceP_adv, float iceP_rot, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_adv, iceP_rot);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_stopBase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_resetOdometer(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_setOdometer(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_state);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_setOdometerPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_x, int iceP_z, float iceP_alpha, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_x, iceP_z, iceP_alpha);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::DifferentialRobotPrx::_iceI_correctOdometer(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_x, int iceP_z, float iceP_alpha, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name);
    outAsync->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_x, iceP_z, iceP_alpha);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::RoboCompGenericBase::HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompDifferentialRobot::DifferentialRobotPrx::_newInstance() const
{
    return ::IceInternal::createProxy<DifferentialRobotPrx>();
}
/// \endcond

const ::std::string&
RoboCompDifferentialRobot::DifferentialRobotPrx::ice_staticId()
{
    return DifferentialRobot::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name = "getBaseState";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name = "getBasePose";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name = "setSpeedBase";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name = "stopBase";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name = "resetOdometer";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name = "setOdometer";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name = "setOdometerPose";

const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name = "correctOdometer";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompDifferentialRobot::upCast(DifferentialRobot* p) { return p; }

void
::IceProxy::RoboCompDifferentialRobot::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< DifferentialRobot>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new DifferentialRobot;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_getBaseState(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_state);
    result->_endReadParams();
}

void IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_end_getBaseState(::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_getBaseState_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_state);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_getBasePose(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_x);
    istr->read(iceP_z);
    istr->read(iceP_alpha);
    result->_endReadParams();
}

void IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_end_getBasePose(::Ice::Int& iceP_x, ::Ice::Int& iceP_z, ::Ice::Float& iceP_alpha, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_getBasePose_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_x);
    istr->read(iceP_z);
    istr->read(iceP_alpha);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_setSpeedBase(::Ice::Float iceP_adv, ::Ice::Float iceP_rot, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_adv);
        ostr->write(iceP_rot);
        result->endWriteParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_setSpeedBase(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_setSpeedBase_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_stopBase(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_stopBase(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_stopBase_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_resetOdometer(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_resetOdometer(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_resetOdometer_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_setOdometer(const ::RoboCompGenericBase::TBaseState& iceP_state, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_state);
        result->endWriteParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_setOdometer(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometer_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_setOdometerPose(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_x);
        ostr->write(iceP_z);
        ostr->write(iceP_alpha);
        result->endWriteParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_setOdometerPose(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_setOdometerPose_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

::Ice::AsyncResultPtr
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_iceI_begin_correctOdometer(::Ice::Int iceP_x, ::Ice::Int iceP_z, ::Ice::Float iceP_alpha, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_x);
        ostr->write(iceP_z);
        ostr->write(iceP_alpha);
        result->endWriteParams();
        result->invoke(iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::end_correctOdometer(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompDifferentialRobot_DifferentialRobot_correctOdometer_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompGenericBase::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::_newInstance() const
{
    return new DifferentialRobot;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompDifferentialRobot::DifferentialRobot::ice_staticId()
{
    return ::RoboCompDifferentialRobot::DifferentialRobot::ice_staticId();
}

RoboCompDifferentialRobot::DifferentialRobot::~DifferentialRobot()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompDifferentialRobot::upCast(DifferentialRobot* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[2] =
{
    "::Ice::Object",
    "::RoboCompDifferentialRobot::DifferentialRobot"
};

}

bool
RoboCompDifferentialRobot::DifferentialRobot::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompDifferentialRobot_DifferentialRobot_ids, iceC_RoboCompDifferentialRobot_DifferentialRobot_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompDifferentialRobot::DifferentialRobot::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[0], &iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[2]);
}

const ::std::string&
RoboCompDifferentialRobot::DifferentialRobot::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompDifferentialRobot::DifferentialRobot::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompDifferentialRobot::DifferentialRobot";
    return typeId;
#else
    return iceC_RoboCompDifferentialRobot_DifferentialRobot_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_getBaseState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::RoboCompGenericBase::TBaseState iceP_state;
    this->getBaseState(iceP_state, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_state);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_getBasePose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Ice::Int iceP_x;
    ::Ice::Int iceP_z;
    ::Ice::Float iceP_alpha;
    this->getBasePose(iceP_x, iceP_z, iceP_alpha, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_x);
    ostr->write(iceP_z);
    ostr->write(iceP_alpha);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_setSpeedBase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Float iceP_adv;
    ::Ice::Float iceP_rot;
    istr->read(iceP_adv);
    istr->read(iceP_rot);
    inS.endReadParams();
    this->setSpeedBase(iceP_adv, iceP_rot, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_stopBase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->stopBase(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_resetOdometer(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->resetOdometer(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_setOdometer(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompGenericBase::TBaseState iceP_state;
    istr->read(iceP_state);
    inS.endReadParams();
    this->setOdometer(iceP_state, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_setOdometerPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_x;
    ::Ice::Int iceP_z;
    ::Ice::Float iceP_alpha;
    istr->read(iceP_x);
    istr->read(iceP_z);
    istr->read(iceP_alpha);
    inS.endReadParams();
    this->setOdometerPose(iceP_x, iceP_z, iceP_alpha, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceD_correctOdometer(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_x;
    ::Ice::Int iceP_z;
    ::Ice::Float iceP_alpha;
    istr->read(iceP_x);
    istr->read(iceP_z);
    istr->read(iceP_alpha);
    inS.endReadParams();
    this->correctOdometer(iceP_x, iceP_z, iceP_alpha, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompDifferentialRobot_DifferentialRobot_all[] =
{
    "correctOdometer",
    "getBasePose",
    "getBaseState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "resetOdometer",
    "setOdometer",
    "setOdometerPose",
    "setSpeedBase",
    "stopBase"
};

}

/// \cond INTERNAL
bool
RoboCompDifferentialRobot::DifferentialRobot::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompDifferentialRobot_DifferentialRobot_all, iceC_RoboCompDifferentialRobot_DifferentialRobot_all + 12, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompDifferentialRobot_DifferentialRobot_all)
    {
        case 0:
        {
            return _iceD_correctOdometer(in, current);
        }
        case 1:
        {
            return _iceD_getBasePose(in, current);
        }
        case 2:
        {
            return _iceD_getBaseState(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        case 7:
        {
            return _iceD_resetOdometer(in, current);
        }
        case 8:
        {
            return _iceD_setOdometer(in, current);
        }
        case 9:
        {
            return _iceD_setOdometerPose(in, current);
        }
        case 10:
        {
            return _iceD_setSpeedBase(in, current);
        }
        case 11:
        {
            return _iceD_stopBase(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompDifferentialRobot::DifferentialRobot::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< DifferentialRobot, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompDifferentialRobot::DifferentialRobot::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< DifferentialRobot, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompDifferentialRobot::_icePatchObjectPtr(DifferentialRobotPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = DifferentialRobotPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(DifferentialRobot::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
