//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `CoppeliaUtils.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <CoppeliaUtils.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[2] =
{
    "::Ice::Object",
    "::RoboCompCoppeliaUtils::CoppeliaUtils"
};
const ::std::string iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ops[] =
{
    "addOrModifyDummy",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name = "addOrModifyDummy";

}

bool
RoboCompCoppeliaUtils::CoppeliaUtils::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids, iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids + 2, s);
}

::std::vector<::std::string>
RoboCompCoppeliaUtils::CoppeliaUtils::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[0], &iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[2]);
}

::std::string
RoboCompCoppeliaUtils::CoppeliaUtils::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompCoppeliaUtils::CoppeliaUtils::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompCoppeliaUtils::CoppeliaUtils";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompCoppeliaUtils::CoppeliaUtils::_iceD_addOrModifyDummy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    TargetTypes iceP_type;
    ::std::string iceP_name;
    PoseType iceP_pose;
    istr->readAll(iceP_type, iceP_name, iceP_pose);
    inS.endReadParams();
    this->addOrModifyDummy(iceP_type, ::std::move(iceP_name), ::std::move(iceP_pose), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompCoppeliaUtils::CoppeliaUtils::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ops, iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ops)
    {
        case 0:
        {
            return _iceD_addOrModifyDummy(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompCoppeliaUtils::CoppeliaUtilsPrx::_iceI_addOrModifyDummy(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, TargetTypes iceP_type, const ::std::string& iceP_name, const PoseType& iceP_pose, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_type, iceP_name, iceP_pose);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompCoppeliaUtils::CoppeliaUtilsPrx::_newInstance() const
{
    return ::IceInternal::createProxy<CoppeliaUtilsPrx>();
}
/// \endcond

const ::std::string&
RoboCompCoppeliaUtils::CoppeliaUtilsPrx::ice_staticId()
{
    return CoppeliaUtils::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name = "addOrModifyDummy";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompCoppeliaUtils::upCast(CoppeliaUtils* p) { return p; }

void
::IceProxy::RoboCompCoppeliaUtils::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< CoppeliaUtils>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new CoppeliaUtils;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompCoppeliaUtils::CoppeliaUtils::_iceI_begin_addOrModifyDummy(::RoboCompCoppeliaUtils::TargetTypes iceP_type, const ::std::string& iceP_name, const ::RoboCompCoppeliaUtils::PoseType& iceP_pose, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_type);
        ostr->write(iceP_name);
        ostr->write(iceP_pose);
        result->endWriteParams();
        result->invoke(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompCoppeliaUtils::CoppeliaUtils::end_addOrModifyDummy(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompCoppeliaUtils_CoppeliaUtils_addOrModifyDummy_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompCoppeliaUtils::CoppeliaUtils::_newInstance() const
{
    return new CoppeliaUtils;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompCoppeliaUtils::CoppeliaUtils::ice_staticId()
{
    return ::RoboCompCoppeliaUtils::CoppeliaUtils::ice_staticId();
}

RoboCompCoppeliaUtils::CoppeliaUtils::~CoppeliaUtils()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompCoppeliaUtils::upCast(CoppeliaUtils* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[2] =
{
    "::Ice::Object",
    "::RoboCompCoppeliaUtils::CoppeliaUtils"
};

}

bool
RoboCompCoppeliaUtils::CoppeliaUtils::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids, iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompCoppeliaUtils::CoppeliaUtils::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[0], &iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[2]);
}

const ::std::string&
RoboCompCoppeliaUtils::CoppeliaUtils::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompCoppeliaUtils::CoppeliaUtils::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompCoppeliaUtils::CoppeliaUtils";
    return typeId;
#else
    return iceC_RoboCompCoppeliaUtils_CoppeliaUtils_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompCoppeliaUtils::CoppeliaUtils::_iceD_addOrModifyDummy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    TargetTypes iceP_type;
    ::std::string iceP_name;
    PoseType iceP_pose;
    istr->read(iceP_type);
    istr->read(iceP_name);
    istr->read(iceP_pose);
    inS.endReadParams();
    this->addOrModifyDummy(iceP_type, iceP_name, iceP_pose, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompCoppeliaUtils_CoppeliaUtils_all[] =
{
    "addOrModifyDummy",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompCoppeliaUtils::CoppeliaUtils::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompCoppeliaUtils_CoppeliaUtils_all, iceC_RoboCompCoppeliaUtils_CoppeliaUtils_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompCoppeliaUtils_CoppeliaUtils_all)
    {
        case 0:
        {
            return _iceD_addOrModifyDummy(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompCoppeliaUtils::CoppeliaUtils::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< CoppeliaUtils, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompCoppeliaUtils::CoppeliaUtils::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< CoppeliaUtils, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompCoppeliaUtils::_icePatchObjectPtr(CoppeliaUtilsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = CoppeliaUtilsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(CoppeliaUtils::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
