//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `JointMotorPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <JointMotorPub.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompJointMotorPub_JointMotorPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompJointMotorPub::JointMotorPub"
};
const ::std::string iceC_RoboCompJointMotorPub_JointMotorPub_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "motorStates"
};
const ::std::string iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name = "motorStates";

}

bool
RoboCompJointMotorPub::JointMotorPub::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompJointMotorPub_JointMotorPub_ids, iceC_RoboCompJointMotorPub_JointMotorPub_ids + 2, s);
}

::std::vector<::std::string>
RoboCompJointMotorPub::JointMotorPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompJointMotorPub_JointMotorPub_ids[0], &iceC_RoboCompJointMotorPub_JointMotorPub_ids[2]);
}

::std::string
RoboCompJointMotorPub::JointMotorPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompJointMotorPub::JointMotorPub::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompJointMotorPub::JointMotorPub";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompJointMotorPub::JointMotorPub::_iceD_motorStates(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompJointMotor::MotorStateMap iceP_mstateMap;
    istr->readAll(iceP_mstateMap);
    inS.endReadParams();
    this->motorStates(::std::move(iceP_mstateMap), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompJointMotorPub::JointMotorPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompJointMotorPub_JointMotorPub_ops, iceC_RoboCompJointMotorPub_JointMotorPub_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompJointMotorPub_JointMotorPub_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_motorStates(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompJointMotorPub::JointMotorPubPrx::_iceI_motorStates(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompJointMotor::MotorStateMap& iceP_mstateMap, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_mstateMap);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompJointMotorPub::JointMotorPubPrx::_newInstance() const
{
    return ::IceInternal::createProxy<JointMotorPubPrx>();
}
/// \endcond

const ::std::string&
RoboCompJointMotorPub::JointMotorPubPrx::ice_staticId()
{
    return JointMotorPub::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name = "motorStates";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompJointMotorPub::upCast(JointMotorPub* p) { return p; }

void
::IceProxy::RoboCompJointMotorPub::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< JointMotorPub>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new JointMotorPub;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompJointMotorPub::JointMotorPub::_iceI_begin_motorStates(const ::RoboCompJointMotor::MotorStateMap& iceP_mstateMap, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_mstateMap);
        result->endWriteParams();
        result->invoke(iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompJointMotorPub::JointMotorPub::end_motorStates(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompJointMotorPub_JointMotorPub_motorStates_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompJointMotorPub::JointMotorPub::_newInstance() const
{
    return new JointMotorPub;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompJointMotorPub::JointMotorPub::ice_staticId()
{
    return ::RoboCompJointMotorPub::JointMotorPub::ice_staticId();
}

RoboCompJointMotorPub::JointMotorPub::~JointMotorPub()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompJointMotorPub::upCast(JointMotorPub* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompJointMotorPub_JointMotorPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompJointMotorPub::JointMotorPub"
};

}

bool
RoboCompJointMotorPub::JointMotorPub::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompJointMotorPub_JointMotorPub_ids, iceC_RoboCompJointMotorPub_JointMotorPub_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompJointMotorPub::JointMotorPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompJointMotorPub_JointMotorPub_ids[0], &iceC_RoboCompJointMotorPub_JointMotorPub_ids[2]);
}

const ::std::string&
RoboCompJointMotorPub::JointMotorPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompJointMotorPub::JointMotorPub::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompJointMotorPub::JointMotorPub";
    return typeId;
#else
    return iceC_RoboCompJointMotorPub_JointMotorPub_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompJointMotorPub::JointMotorPub::_iceD_motorStates(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompJointMotor::MotorStateMap iceP_mstateMap;
    istr->read(iceP_mstateMap);
    inS.endReadParams();
    this->motorStates(iceP_mstateMap, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompJointMotorPub_JointMotorPub_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "motorStates"
};

}

/// \cond INTERNAL
bool
RoboCompJointMotorPub::JointMotorPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompJointMotorPub_JointMotorPub_all, iceC_RoboCompJointMotorPub_JointMotorPub_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompJointMotorPub_JointMotorPub_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_motorStates(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompJointMotorPub::JointMotorPub::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< JointMotorPub, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompJointMotorPub::JointMotorPub::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< JointMotorPub, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompJointMotorPub::_icePatchObjectPtr(JointMotorPubPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = JointMotorPubPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(JointMotorPub::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
