//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `KinovaArmPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <KinovaArmPub.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompKinovaArmPub::KinovaArmPub"
};
const ::std::string iceC_RoboCompKinovaArmPub_KinovaArmPub_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newArmState"
};
const ::std::string iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name = "newArmState";

}

bool
RoboCompKinovaArmPub::KinovaArmPub::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompKinovaArmPub_KinovaArmPub_ids, iceC_RoboCompKinovaArmPub_KinovaArmPub_ids + 2, s);
}

::std::vector<::std::string>
RoboCompKinovaArmPub::KinovaArmPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[0], &iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[2]);
}

::std::string
RoboCompKinovaArmPub::KinovaArmPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompKinovaArmPub::KinovaArmPub::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompKinovaArmPub::KinovaArmPub";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompKinovaArmPub::KinovaArmPub::_iceD_newArmState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    TArmState iceP_armstate;
    istr->readAll(iceP_armstate);
    inS.endReadParams();
    this->newArmState(::std::move(iceP_armstate), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompKinovaArmPub::KinovaArmPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompKinovaArmPub_KinovaArmPub_ops, iceC_RoboCompKinovaArmPub_KinovaArmPub_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompKinovaArmPub_KinovaArmPub_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newArmState(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompKinovaArmPub::KinovaArmPubPrx::_iceI_newArmState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const TArmState& iceP_armstate, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_armstate);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompKinovaArmPub::KinovaArmPubPrx::_newInstance() const
{
    return ::IceInternal::createProxy<KinovaArmPubPrx>();
}
/// \endcond

const ::std::string&
RoboCompKinovaArmPub::KinovaArmPubPrx::ice_staticId()
{
    return KinovaArmPub::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name = "newArmState";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompKinovaArmPub::upCast(KinovaArmPub* p) { return p; }

void
::IceProxy::RoboCompKinovaArmPub::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< KinovaArmPub>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new KinovaArmPub;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompKinovaArmPub::KinovaArmPub::_iceI_begin_newArmState(const ::RoboCompKinovaArmPub::TArmState& iceP_armstate, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_armstate);
        result->endWriteParams();
        result->invoke(iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompKinovaArmPub::KinovaArmPub::end_newArmState(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompKinovaArmPub_KinovaArmPub_newArmState_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompKinovaArmPub::KinovaArmPub::_newInstance() const
{
    return new KinovaArmPub;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompKinovaArmPub::KinovaArmPub::ice_staticId()
{
    return ::RoboCompKinovaArmPub::KinovaArmPub::ice_staticId();
}

RoboCompKinovaArmPub::KinovaArmPub::~KinovaArmPub()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompKinovaArmPub::upCast(KinovaArmPub* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompKinovaArmPub::KinovaArmPub"
};

}

bool
RoboCompKinovaArmPub::KinovaArmPub::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompKinovaArmPub_KinovaArmPub_ids, iceC_RoboCompKinovaArmPub_KinovaArmPub_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompKinovaArmPub::KinovaArmPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[0], &iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[2]);
}

const ::std::string&
RoboCompKinovaArmPub::KinovaArmPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompKinovaArmPub::KinovaArmPub::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompKinovaArmPub::KinovaArmPub";
    return typeId;
#else
    return iceC_RoboCompKinovaArmPub_KinovaArmPub_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompKinovaArmPub::KinovaArmPub::_iceD_newArmState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    TArmState iceP_armstate;
    istr->read(iceP_armstate);
    inS.endReadParams();
    this->newArmState(iceP_armstate, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompKinovaArmPub_KinovaArmPub_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newArmState"
};

}

/// \cond INTERNAL
bool
RoboCompKinovaArmPub::KinovaArmPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompKinovaArmPub_KinovaArmPub_all, iceC_RoboCompKinovaArmPub_KinovaArmPub_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompKinovaArmPub_KinovaArmPub_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newArmState(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompKinovaArmPub::KinovaArmPub::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< KinovaArmPub, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompKinovaArmPub::KinovaArmPub::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< KinovaArmPub, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompKinovaArmPub::_icePatchObjectPtr(KinovaArmPubPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = KinovaArmPubPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(KinovaArmPub::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
