//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `LaserPub.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <LaserPub.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompLaserPub_LaserPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLaserPub::LaserPub"
};
const ::std::string iceC_RoboCompLaserPub_LaserPub_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "pushLaserData"
};
const ::std::string iceC_RoboCompLaserPub_LaserPub_pushLaserData_name = "pushLaserData";

}

bool
RoboCompLaserPub::LaserPub::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompLaserPub_LaserPub_ids, iceC_RoboCompLaserPub_LaserPub_ids + 2, s);
}

::std::vector<::std::string>
RoboCompLaserPub::LaserPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompLaserPub_LaserPub_ids[0], &iceC_RoboCompLaserPub_LaserPub_ids[2]);
}

::std::string
RoboCompLaserPub::LaserPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompLaserPub::LaserPub::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompLaserPub::LaserPub";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompLaserPub::LaserPub::_iceD_pushLaserData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompLaser::TLaserData iceP_laserData;
    istr->readAll(iceP_laserData);
    inS.endReadParams();
    this->pushLaserData(::std::move(iceP_laserData), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompLaserPub::LaserPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompLaserPub_LaserPub_ops, iceC_RoboCompLaserPub_LaserPub_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompLaserPub_LaserPub_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_pushLaserData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLaserPub::LaserPubPrx::_iceI_pushLaserData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompLaser::TLaserData& iceP_laserData, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompLaserPub_LaserPub_pushLaserData_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_laserData);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompLaserPub::LaserPubPrx::_newInstance() const
{
    return ::IceInternal::createProxy<LaserPubPrx>();
}
/// \endcond

const ::std::string&
RoboCompLaserPub::LaserPubPrx::ice_staticId()
{
    return LaserPub::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompLaserPub_LaserPub_pushLaserData_name = "pushLaserData";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompLaserPub::upCast(LaserPub* p) { return p; }

void
::IceProxy::RoboCompLaserPub::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< LaserPub>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new LaserPub;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompLaserPub::LaserPub::_iceI_begin_pushLaserData(const ::RoboCompLaser::TLaserData& iceP_laserData, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompLaserPub_LaserPub_pushLaserData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompLaserPub_LaserPub_pushLaserData_name, ::Ice::Idempotent, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_laserData);
        result->endWriteParams();
        result->invoke(iceC_RoboCompLaserPub_LaserPub_pushLaserData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompLaserPub::LaserPub::end_pushLaserData(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompLaserPub_LaserPub_pushLaserData_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompLaserPub::LaserPub::_newInstance() const
{
    return new LaserPub;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompLaserPub::LaserPub::ice_staticId()
{
    return ::RoboCompLaserPub::LaserPub::ice_staticId();
}

RoboCompLaserPub::LaserPub::~LaserPub()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompLaserPub::upCast(LaserPub* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompLaserPub_LaserPub_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLaserPub::LaserPub"
};

}

bool
RoboCompLaserPub::LaserPub::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompLaserPub_LaserPub_ids, iceC_RoboCompLaserPub_LaserPub_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompLaserPub::LaserPub::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompLaserPub_LaserPub_ids[0], &iceC_RoboCompLaserPub_LaserPub_ids[2]);
}

const ::std::string&
RoboCompLaserPub::LaserPub::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompLaserPub::LaserPub::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompLaserPub::LaserPub";
    return typeId;
#else
    return iceC_RoboCompLaserPub_LaserPub_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompLaserPub::LaserPub::_iceD_pushLaserData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompLaser::TLaserData iceP_laserData;
    istr->read(iceP_laserData);
    inS.endReadParams();
    this->pushLaserData(iceP_laserData, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompLaserPub_LaserPub_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "pushLaserData"
};

}

/// \cond INTERNAL
bool
RoboCompLaserPub::LaserPub::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompLaserPub_LaserPub_all, iceC_RoboCompLaserPub_LaserPub_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompLaserPub_LaserPub_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_pushLaserData(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompLaserPub::LaserPub::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< LaserPub, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompLaserPub::LaserPub::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< LaserPub, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompLaserPub::_icePatchObjectPtr(LaserPubPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = LaserPubPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(LaserPub::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
