// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GraphRequest.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "GraphRequest.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

GraphRequest::GraphRequest()
{
    // m_from com.eprosima.idl.parser.typecode.StringTypeCode@520a3426
    m_from ="";

}

GraphRequest::~GraphRequest()
{
}

GraphRequest::GraphRequest(const GraphRequest &x)
{
    m_from = x.m_from;
}

GraphRequest::GraphRequest(GraphRequest &&x)
{
    m_from = std::move(x.m_from);
}

GraphRequest& GraphRequest::operator=(const GraphRequest &x)
{

    m_from = x.m_from;

    return *this;
}

GraphRequest& GraphRequest::operator=(GraphRequest &&x)
{

    m_from = std::move(x.m_from);

    return *this;
}

size_t GraphRequest::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    return current_alignment - initial_alignment;
}

size_t GraphRequest::getCdrSerializedSize(const GraphRequest& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.from().size() + 1;

    return current_alignment - initial_alignment;
}

void GraphRequest::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_from;
}

void GraphRequest::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_from;
}

/*!
 * @brief This function copies the value in member from
 * @param _from New value to be copied in member from
 */
void GraphRequest::from(const std::string &_from)
{
m_from = _from;
}

/*!
 * @brief This function moves the value in member from
 * @param _from New value to be moved in member from
 */
void GraphRequest::from(std::string &&_from)
{
m_from = std::move(_from);
}

/*!
 * @brief This function returns a constant reference to member from
 * @return Constant reference to member from
 */
const std::string& GraphRequest::from() const
{
    return m_from;
}

/*!
 * @brief This function returns a reference to member from
 * @return Reference to member from
 */
std::string& GraphRequest::from()
{
    return m_from;
}

size_t GraphRequest::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;



    return current_align;
}

bool GraphRequest::isKeyDefined()
{
   return false;
}

void GraphRequest::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
}
